### ISSUE TITLE
Artifacts on the chart

### ISSUE THREAD

**Issue by OlegichSha** [royben/RealTimeGraphX#7]
![Артефакты на графике](https://user-images.githubusercontent.com/30231696/91615172-ab300b80-e98b-11ea-9f76-9707b88f016b.jpg)
how do I fix it?

**Comment by royben** [comment]
Hi,
I have fixed this issue a long time ago just didn't had time to update.

I just committed some major improvements on the library:

Fixed artifacts on WpfGraphSurface drawing.
Fixed issue with double/float data point infinity.
Fixed issue with Int32 data point.
Added new DateTime data point.
Improved support for panning/zooming while paused.
Improved "Clear" functionality.
Added DataSeries CurrentValue property.

Please get the latest changes and try again.

Thanks.

**Comment by OlegichSha** [comment]
Hello. 
Thank you for the updates. I also found a defect when the value does not change to Y-axis the graph falls to zero.

Perhaps this is not a defect, and there are settings?

Thanks.

**Comment by royben** [comment]
When the graph Y range is set to Auto, it will adjust the min/max values based on the current values in the graph.
If you can estimate the min/max values your self the try settings
Controller.Range.AutoY = false;

Otherwise I guess I can implement a small min/max margins when all y values are equal.

**Comment by royben** [comment]
https://github.com/royben/RealTimeGraphX/commit/1edb9094d4e358270af353b270d92c97376542b2
